# Generated by Django 3.0.7 on 2020-08-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200723_0509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
