# Generated by Django 3.0.7 on 2020-08-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
    ]
