# Generated by Django 3.0.7 on 2020-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20200812_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
