# Generated by Django 3.0.7 on 2020-08-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_item_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='short_des',
            field=models.TextField(null=True),
        ),
    ]
