# Generated by Django 3.0.7 on 2020-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_item_short_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warrenty',
            field=models.TextField(null=True),
        ),
    ]
