# Generated by Django 3.0.7 on 2020-08-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_item_warrenty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
