# Generated by Django 3.1.2 on 2020-12-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='productid',
            field=models.CharField(blank=True, max_length=53, null=True),
        ),
    ]
