# Generated by Django 3.1.2 on 2020-12-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20201229_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
