# Generated by Django 3.1.2 on 2020-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_thankyou'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankyou',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='thankyou',
            name='picture',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
