# Generated by Django 3.1.2 on 2020-12-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_auto_20201229_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThankYou',
        ),
    ]
