# Generated by Django 3.1.2 on 2020-12-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0020_delete_thankyou'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('picture', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
